import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getEverkeepApi } from '@renderer/lib/api'
import { useVaultStore } from '@renderer/state/vaultStore'
import type { SharedSnapshot, SharingAccount as Account, SharingStatus, SyncConflicts } from '@shared/sharing'
import { SharingAccount, message } from '../../sharing/SharingAccount'
import { SharingControls } from '../../sharing/SharingControls'
import '../../sharing/sharing.css'
const client = getEverkeepApi().sharing
function describe(value: string) {
  try { const record = JSON.parse(value); return record ? `${record.title}\n${Object.values(record.fields as Record<string, { label: string; value: string; sensitive?: boolean }>).filter(field => field.value).map(field => `${field.label}: ${field.sensitive ? '•••••••• (sensitive value changed)' : field.value}`).join('\n')}` : 'Record removed' } catch { return value }
}
export function VaultSharingPage() {
  const session = useVaultStore(state => state.session)
  const [account, setAccount] = useState<Account | null>(null), [status, setStatus] = useState<SharingStatus | null>(null), [snapshot, setSnapshot] = useState<SharedSnapshot | null>(null)
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [conflicts, setConflicts] = useState<SyncConflicts | null>(null), [choices, setChoices] = useState<Record<string, 'local' | 'shared'>>({})
  const refresh = useCallback(async () => { const [next, records, conflict] = await Promise.all([client.status(), client.snapshot(), client.conflicts()]); setStatus(next); setSnapshot(records); setConflicts(conflict) }, [])
  useEffect(() => { void refresh().catch(error => setError(message(error))); const timer = setInterval(() => void refresh().catch(() => {}), 15000); return () => clearInterval(timer) }, [refresh, session?.metadata.id])
  const accountChanged = useCallback((value: Account | null) => { setAccount(value); void refresh().catch(error => setError(message(error))) }, [refresh])
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(''); try { await action(); await refresh() } catch (error) { setError(message(error)); await refresh().catch(() => {}) } finally { setBusy(false) } }
  return <div className="ek-sharing" style={{ padding: 0 }} key={session?.metadata.id}>
    <h1>Review &amp; share</h1><p>Choose who can see your vault, decide whether they can edit, and email them a link.</p>
    <div className="ek-card" style={{ padding: '12px 16px' }}><div className="ek-row ek-between"><strong>Saved on this computer</strong><button disabled={busy} onClick={() => void run(async () => { const path = await client.saveCopy(); if (path) setNotice(`Everkeep file saved to ${path}. This is a separate copy; future changes stay in the original file and the online shared vault.`) })}>Save an Everkeep file</button></div><p className="ek-path" style={{ margin: '6px 0' }}>{status?.local?.filePath || session?.filePath}</p><details><summary className="ek-muted" style={{ cursor: 'pointer' }}>Saving details &amp; Show in folder</summary><p className="ek-muted">Changes are saved here automatically. Save an Everkeep file to keep a separate copy.</p><button disabled={busy} onClick={() => void run(() => client.reveal())}>Show in folder</button></details></div>
    <div className="ek-row ek-between"><Link to="/check">Review information before sharing</Link><Link to="/shared">My vaults &amp; Shared with me</Link></div>
    {error && <p className="ek-error" role="alert">{error}</p>}{notice && <p className="ek-success" role="status">{notice}</p>}
    <SharingAccount client={client} onChange={accountChanged} />
    {account && !status?.local?.sharedId && <section className="ek-card"><h2>Enable ongoing sharing</h2><p>You will own this online vault as <strong>{account.email}</strong>. The person described in the vault remains unchanged.</p><p>Everkeep will upload the vault’s records and attachments to its sharing service. The service encrypts stored information and checks each recipient’s verified identity and permissions. Only information you grant is visible to recipients.</p><p className="ek-muted">Updates synchronize while this original vault is open, unlocked, and connected. Saving a file to a folder alone does not provide ongoing online access.</p><button className="primary" disabled={busy} onClick={() => void run(() => client.publish())}>{busy ? 'Preparing shared vault…' : 'Enable online sharing'}</button></section>}
    {status?.local?.sharedId && account && !status.local.ownsShared && <p className="ek-error">This shared vault belongs to a different account. Sign in as its owner to synchronize the original file, or use Shared with me for your recipient access.</p>}
    {conflicts && <section className="ek-card"><h2>Choose which changes to keep</h2><p>These records changed locally and online. Review each version before synchronizing.</p>{conflicts.items.map(item => <fieldset className="ek-card" key={item.id}><legend>Conflicting record</legend><div className="ek-columns"><label><input type="radio" name={item.id} checked={choices[item.id] === 'local'} onChange={() => setChoices({ ...choices, [item.id]: 'local' })} />Keep local version<pre>{describe(item.local)}</pre></label><label><input type="radio" name={item.id} checked={choices[item.id] === 'shared'} onChange={() => setChoices({ ...choices, [item.id]: 'shared' })} />Keep shared version<pre>{describe(item.shared)}</pre></label></div></fieldset>)}<button className="primary" disabled={busy || conflicts.items.some(item => !choices[item.id])} onClick={() => void run(() => client.sync({ revision: conflicts.revision, fingerprint: conflicts.fingerprint, choices }))}>Save these choices and sync</button></section>}
    {account && status?.local?.ownsShared && status.local.sharedId && snapshot && <SharingControls key={`${session?.metadata.id}-${account.id}`} client={client} id={status.local.sharedId} snapshot={snapshot} owner={account.email} url={status.url} allowPassword={session?.metadata.isPasswordProtected} />}
    {status?.local?.sharedId && <section className="ek-card"><h2>Online shared vault</h2><p className="ek-path">{status.url}/#vault/{status.local.sharedId}</p><p role="status">{status.local.state === 'synced' ? 'Synchronized' : status.local.state === 'syncing' ? 'Synchronizing…' : status.local.state === 'conflict' ? 'Changes need your review' : 'Waiting to synchronize'}{status.local.lastSyncedAt ? ` · Last synced ${new Date(status.local.lastSyncedAt).toLocaleString()}` : ''}</p>{status.local.error && <p className="ek-error">{status.local.error}</p>}<button disabled={busy} onClick={() => void run(() => client.sync())}>Sync now</button><p className="ek-muted">Recipients see the latest successfully synchronized version. Your local file remains at the location above.</p></section>}
    <section className="ek-card"><h2>Other ways to keep or share information</h2><p><Link to="/export">Export an unencrypted readable copy</Link></p><p className="ek-muted">A standalone document for printing or saving as PDF. It does not receive updates and cannot enforce recipient access.</p><p><Link to="/backup">Saved copies, restoration &amp; access practice</Link></p><p><Link to="/start-here">Default packet instructions</Link></p></section>
  </div>
}
