import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getEverkeepApi } from '@renderer/lib/api'
import { useVaultStore } from '@renderer/state/vaultStore'
import type { SharedSnapshot, SharingAccount as Account, SharingStatus, SyncConflicts } from '@shared/sharing'
import { SharingAccount, message } from '../../sharing/SharingAccount'
import { SharingControls } from '../../sharing/SharingControls'
import '../../sharing/sharing.css'
const client = getEverkeepApi().sharing
function describe(value: string) {
  try { const record = JSON.parse(value); return record ? `${record.title}\n${Object.values(record.fields as Record<string, { label: string; value: string; sensitive?: boolean }>).filter(field => field.value).map(field => `${field.label}: ${field.sensitive ? '•••••••• (sensitive value changed)' : field.value}`).join('\n')}` : 'Record removed' } catch { return value }
}
export function VaultSharingPage() {
  const session = useVaultStore(state => state.session)
  const [account, setAccount] = useState<Account | null>(null), [status, setStatus] = useState<SharingStatus | null>(null), [snapshot, setSnapshot] = useState<SharedSnapshot | null>(null)
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [conflicts, setConflicts] = useState<SyncConflicts | null>(null), [choices, setChoices] = useState<Record<string, 'local' | 'shared'>>({})
  const refresh = useCallback(async () => { const [next, records, conflict] = await Promise.all([client.status(), client.snapshot(), client.conflicts()]); setStatus(next); setSnapshot(records); setConflicts(conflict) }, [])
  useEffect(() => { void refresh().catch(error => setError(message(error))); const timer = setInterval(() => void refresh().catch(() => {}), 15000); return () => clearInterval(timer) }, [refresh, session?.metadata.id])
  const accountChanged = useCallback((value: Account | null) => { setAccount(value); void refresh().catch(error => setError(message(error))) }, [refresh])
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(''); try { await action(); await refresh() } catch (error) { setError(message(error)); await refresh().catch(() => {}) } finally { setBusy(false) } }
  return <div className="ek-sharing" style={{ padding: 0 }} key={session?.metadata.id}>
    <h1>Review &amp; share</h1><p>Keep your vault as a file, choose who can open it, and optionally enable hosted storage.</p>
    <div className="ek-card" style={{ padding: '12px 16px' }}><div className="ek-row ek-between"><strong>Saved on this computer</strong><button disabled={busy} onClick={() => void run(async () => { const path = await client.saveCopy(); if (path) setNotice(`Everkeep file saved to ${path}. This is a personal copy with the original password protection. It does not enforce recipient permissions; use Save a file for recipients below when sharing.`) })}>Save an Everkeep file</button></div><p className="ek-path" style={{ margin: '6px 0' }}>{status?.local?.filePath || session?.filePath}</p><details><summary className="ek-muted" style={{ cursor: 'pointer' }}>Saving details &amp; Show in folder</summary><p className="ek-muted">Changes are saved here automatically. This personal copy retains the original protection and does not enforce recipient permissions. Use Save a file for recipients for access-controlled sharing.</p><button disabled={busy} onClick={() => void run(() => client.reveal())}>Show in folder</button></details></div>
    <div className="ek-row ek-between"><Link to="/check">Review information before sharing</Link><Link to="/shared">My vaults &amp; Shared with me</Link></div>
    {error && <p className="ek-error" role="alert">{error}</p>}{notice && <p className="ek-success" role="status">{notice}</p>}
    <SharingAccount client={client} onChange={accountChanged} />
    {account && !status?.local?.sharedId && <section className="ek-card"><h2>Register ownership and access</h2><p>Register <strong>{account.email}</strong> as this vault’s owner. Saving your original file never requires registration or an upload.</p><p>Everkeep stores your verified identity, vault ID and name, permissions, and protected record keys. Your records and attachments stay in the file you distribute yourself.</p><button className="primary" disabled={busy} onClick={() => void run(() => client.registerFile())}>{busy ? 'Registering…' : 'Register file-based sharing'}</button></section>}
    {account && status?.local?.ownsShared && <section className="ek-card"><h2>Share an Everkeep file</h2><p>Owner: {status.local.ownerEmail || account.email}. Save an access-controlled copy, put it in Google Drive or another location, then include that location in your invitation instructions below.</p><p>Recipients open the file and verify their email. Each record and its attachments are encrypted separately; the service only releases keys for their permitted records. The original vault password cannot unlock this copy.</p><button className="primary" disabled={busy} onClick={() => void run(async () => { const path = await client.saveSharedFile(); if (path) setNotice(`Access-controlled file saved to ${path}. Give this file to your recipients; its contents were not uploaded.`) })}>Save a file for recipients</button><p className="ek-muted">Recipients need internet access to verify permissions. Copies do not synchronize; collaborators must save and return an updated file separately. Revoking access cannot erase information or keys already obtained.</p></section>}
    {account && status?.local?.ownsShared && status.local.storage === 'file' && <section className="ek-card"><h2>Optional: store with Everkeep</h2><p>Upload records and attachments for access without a file and ongoing synchronization. File-based access does not require this.</p><button disabled={busy} onClick={() => void run(() => client.publish())}>Enable online sharing</button></section>}
    {status?.local?.sharedId && account && !status.local.ownsShared && <p className="ek-error">This shared vault belongs to a different account. Sign in as its owner to synchronize the original file, or use Shared with me for your recipient access.</p>}
    {conflicts && <section className="ek-card"><h2>Choose which changes to keep</h2><p>These records changed locally and online. Review each version before synchronizing.</p>{conflicts.items.map(item => <fieldset className="ek-card" key={item.id}><legend>Conflicting record</legend><div className="ek-columns"><label><input type="radio" name={item.id} checked={choices[item.id] === 'local'} onChange={() => setChoices({ ...choices, [item.id]: 'local' })} />Keep local version<pre>{describe(item.local)}</pre></label><label><input type="radio" name={item.id} checked={choices[item.id] === 'shared'} onChange={() => setChoices({ ...choices, [item.id]: 'shared' })} />Keep shared version<pre>{describe(item.shared)}</pre></label></div></fieldset>)}<button className="primary" disabled={busy || conflicts.items.some(item => !choices[item.id])} onClick={() => void run(() => client.sync({ revision: conflicts.revision, fingerprint: conflicts.fingerprint, choices }))}>Save these choices and sync</button></section>}
    {account && status?.local?.ownsShared && status.local.sharedId && snapshot && <SharingControls key={`${session?.metadata.id}-${account.id}`} client={client} id={status.local.sharedId} snapshot={snapshot} owner={account.email} url={status.url} storage={status.local.storage} allowPassword={false} />}
    {status?.local?.sharedId && status.local.storage !== 'file' && <section className="ek-card"><h2>Online shared vault</h2><p className="ek-path">{status.url}/#vault/{status.local.sharedId}</p><p role="status">{status.local.state === 'synced' ? 'Synchronized' : status.local.state === 'syncing' ? 'Synchronizing…' : status.local.state === 'conflict' ? 'Changes need your review' : 'Waiting to synchronize'}{status.local.lastSyncedAt ? ` · Last synced ${new Date(status.local.lastSyncedAt).toLocaleString()}` : ''}</p>{status.local.error && <p className="ek-error">{status.local.error}</p>}<button disabled={busy} onClick={() => void run(() => client.sync())}>Sync now</button><p className="ek-muted">Recipients see the latest successfully synchronized version. Your local file remains at the location above.</p></section>}
    <section className="ek-card"><h2>Other ways to keep or share information</h2><p><Link to="/export">Export an unencrypted readable copy</Link></p><p className="ek-muted">A standalone document for printing or saving as PDF. It does not receive updates and cannot enforce recipient access.</p><p><Link to="/backup">Saved copies, restoration &amp; access practice</Link></p><p><Link to="/start-here">Default packet instructions</Link></p></section>
  </div>
}
