import { useEffect, useRef, useState } from 'react'
import { invitationText, type SharedMembership, type SharedSnapshot, type SharingClient, type ShareInvitation } from '../shared/sharing'
import { message } from './SharingAccount'
export function SharingControls({ client, id, snapshot, owner, url, allowPassword = false }: { client: SharingClient; id: string; snapshot: SharedSnapshot; owner: string; url: string; allowPassword?: boolean }) {
  const [email, setEmail] = useState(''), [all, setAll] = useState(true), [selected, setSelected] = useState<string[]>([]), [canEdit, setCanEdit] = useState(false)
  const [instructions, setInstructions] = useState(''), [includePassword, setIncludePassword] = useState(false), [password, setPassword] = useState(''), [preview, setPreview] = useState<ShareInvitation | null>(null)
  const [members, setMembers] = useState<SharedMembership[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const latest = useRef(true)
  async function refresh() { setMembers(await client.members(id)) }
  useEffect(() => { latest.current = true; client.members(id).then(value => { if (latest.current) setMembers(value) }).catch(error => { if (latest.current) setError(message(error)) }); return () => { latest.current = false } }, [client, id])
  const people = snapshot.records.filter(record => record.kind === 'people' && record.fields.email?.value)
  async function changeMember(member: SharedMembership, action: 'revoke' | 'edit') {
    if (action === 'revoke' && !window.confirm(`Remove ${member.email}'s future access? Information already viewed or downloaded cannot be taken back.`)) return
    setBusy(true); setError('')
    try { if (action === 'revoke') await client.revoke(id, member.email); else await client.grant(id, { email: member.email, scope: member.scope, canEdit: !member.canEdit }); await refresh() } catch (error) { setError(message(error)) } finally { setBusy(false) }
  }
  return <>
    <section className="ek-card"><h2>Who would you like to share with?</h2>
      {error && <p className="ek-error" role="alert">{error}</p>}{success && <p className="ek-success" role="status">{success}</p>}
      {preview ? <><h3>Review the invitation to {preview.email}</h3><pre>{invitationText(snapshot.name, owner, `${url}/#vault/${id}`, preview)}</pre><p className="ek-muted">{preview.password ? 'This email includes the local file password. Anyone who can read the email will have it.' : 'No local vault password is included.'}</p><div className="ek-row"><button className="primary" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await client.invite(id, preview); setSuccess(`Invitation emailed to ${preview.email}. They must verify that email address before opening the vault.`); setPreview(null); setPassword(''); setIncludePassword(false); await refresh() } catch (error) { setError(message(error)) } finally { setBusy(false) } }}>{busy ? 'Sending…' : 'Send invitation'}</button><button disabled={busy} onClick={() => setPreview(null)}>Back to settings</button></div></> : <form onSubmit={event => { event.preventDefault(); setError(''); setSuccess(''); setPreview({ email: email.trim().toLowerCase(), scope: all ? { type: 'all' } : { type: 'selected', recordIds: selected }, canEdit, instructions, ...(includePassword ? { password } : {}), requestId: crypto.randomUUID() }) }}>
        {people.length > 0 && <label><span>Choose a contact (optional)</span><select defaultValue="" onChange={event => setEmail(event.target.value)}><option value="">Enter an email below</option>{people.map(person => <option key={person.id} value={person.fields.email.value}>{person.title} — {person.fields.email.value}</option>)}</select></label>}
        <label><span>Recipient email</span><input type="email" required value={email} onChange={event => setEmail(event.target.value)} /></label>
        <fieldset><legend>What can they see?</legend><label><input type="radio" name="scope" checked={all} onChange={() => setAll(true)} />Entire vault · view only by default</label><label><input type="radio" name="scope" checked={!all} onChange={() => setAll(false)} />Only information I choose</label></fieldset>
        {all ? <p className="ek-muted">Includes all current and future records, private notes, sensitive values, access instructions, and their attached files.</p> : <><p>{selected.length} of {snapshot.records.length} records selected. New records will remain private until you select them.</p><div className="ek-records">{snapshot.records.map(record => <label key={record.id}><input type="checkbox" checked={selected.includes(record.id)} onChange={event => setSelected(value => event.target.checked ? [...value, record.id] : value.filter(id => id !== record.id))} />{record.title} <small>· {record.section}{record.attachments.length ? ` · ${record.attachments.length} files` : ''}</small></label>)}</div><p className="ek-muted">Each selected record includes its fields and attachments, including any sensitive values in that record.</p></>}
        <label><input type="checkbox" checked={canEdit} onChange={event => setCanEdit(event.target.checked)} />Allow this person to edit shared information</label><p className="ek-muted">{canEdit ? 'A collaborator can update editable fields in these records. Only you manage invitations and access. Relationships and adding or removing records are managed in the original vault.' : 'They can read the shared information and download its attachments. They cannot edit your vault.'}</p>
        <label><span>Instructions for the recipient (optional)</span><textarea rows={3} maxLength={4000} value={instructions} onChange={event => setInstructions(event.target.value)} placeholder="Add anything they should know about finding or using the vault." /></label>
        {allowPassword && <><label><input type="checkbox" checked={includePassword} onChange={event => { setIncludePassword(event.target.checked); if (!event.target.checked) setPassword('') }} />Include the local vault file password in this email</label>{includePassword && <label><span>Local vault password</span><input type="password" autoComplete="off" required value={password} onChange={event => setPassword(event.target.value)} /><small>The online link uses verified email access. This password is only for a separately saved vault file and is not stored with the invitation.</small></label>}</>}
        <button className="primary" disabled={busy || (!all && selected.length === 0)}>Review email and share</button>
      </form>}
    </section>
    <section className="ek-card"><h2>People with access</h2><p className="ek-muted">Owner: {owner}. Opening a shared vault does not transfer ownership.</p>{members.filter(member => member.status !== 'revoked').length === 0 && <p>No recipients yet.</p>}{members.filter(member => member.status !== 'revoked').map(member => <div className="ek-card" key={member.email}><div className="ek-row ek-between"><strong>{member.email}</strong><span className="ek-badge">{member.status === 'pending' ? 'Invitation pending' : 'Active'}</span></div><p>{member.scope.type === 'all' ? 'Entire vault' : `${member.scope.recordIds.length} selected records`} · {member.canEdit ? 'Can edit' : 'View only'} · Email {member.emailStatus}</p><div className="ek-row"><button disabled={busy} onClick={() => void changeMember(member, 'edit')}>{member.canEdit ? 'Make view only' : 'Allow editing'}</button><button disabled={busy} onClick={() => { setEmail(member.email); setAll(member.scope.type === 'all'); setSelected(member.scope.type === 'selected' ? member.scope.recordIds : []); setCanEdit(member.canEdit); setPreview(null); window.scrollTo({ top: 0, behavior: 'smooth' }) }}>Change contents / resend</button><button disabled={busy} onClick={() => void changeMember(member, 'revoke')}>Remove access</button></div></div>)}</section>
  </>
}
